# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-1'

menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Writing', path: 'menu', url: 'writing.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://github.com/dszv'}
# - {icon: 'twitter', link: 'https://twitter.com/paululele'}
# - {icon: 'linkedin', link: 'http://www.linkedin.com/in/lenpaul/'}
- {icon: 'flask', link: 'https://arxiv.org/abs/2001.02471'}
- {icon: 'envelope', link: 'mailto:diego.suarez@uni.pe'}
# - {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  previous_page: 'Older'
  next_page: 'Newer'

sharing_button_prompt: 'Share'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
